name: Clang 10.0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config: [Debug, Release]

    steps:
      - uses: actions/checkout@v2

      - name: Install Compiler
        run: |
          sudo apt install clang
          clang --version
          sudo pip install gcovr

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          export CC=`which clang`
          export CXX=`which clang++`
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.config}}

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config ${{matrix.config}}

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest --build-config ${{matrix.config}} --rerun-failed --output-on-failure
